x-default-tasks: &default-tasks
  cronjobs:
    - name: drush cron
      schedule: "*/15 * * * *"
      command: drush cron
      service: cli
    - name: drush cron native
      schedule: "0 * * * *"
      command: drush cron
      service: cli

docker-compose-yaml: docker-compose.yml

project: drupal8-example-advanced

tasks:
#   pre-rollout:
#     - run:
#         name: drush sql-dump
#         command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
#         service: cli

  post-rollout:
    # - run:
    #     name: drush cim
    #     command: drush -y cim
    #     service: cli
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli

environments:
  main:
    routes:
      # nginx.main.salvo-d8.de3.amazee.io
      - nginx:
        - main-salvo-d8.duckdns.org:
            tls-acme: "true"
            insecure: Redirect
            annotations:
              nginx.ingress.kubernetes.io/server-snippet: |
                add_header X-branch "#main";
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
      - name: drush cron native
        schedule: "0 * * * *"
        command: drush cron
        service: cli

  stage:
    routes:
      # nginx.stage.salvo-d8.de3.amazee.io
      - nginx:
        - stage-salvo-d8.duckdns.org:
            tls-acme: "true"
            insecure: Redirect
            annotations:
              nginx.ingress.kubernetes.io/server-snippet: |
                add_header X-branch "#stage";
    << : *default-tasks
    cronjobs:
      - name: ls
        schedule: "*/15 * * * *"
        command: ls
        service: cli      