docker-compose-yaml: docker-compose.yml

project: drupal8-example-advanced

tasks:
#   pre-rollout:
#     - run:
#         name: drush sql-dump
#         command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
#         service: cli

  post-rollout:
    # - run:
    #     name: drush cim
    #     command: drush -y cim
    #     service: cli
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli



environments:
  9.x:
    routes:
      - nginx:
        - drupal9.amazee.io:
            annotations:
              nginx.ingress.kubernetes.io/server-snippet: |
                add_header X-BlackLivesMatter ⬛️⬛️⬛️⬛️⬛️⬛️;
                add_header X-BlackLivesMatter ⬛️⬛️⬛️⬛️⬛️⬛️;
                add_header X-BlackLivesMatter ⬛️⬛️⬛️⬛️⬛️⬛️;
                add_header X-BlackLivesMatter ⬛️⬛️⬛️⬛️⬛️⬛️;
                add_header X-BlackLivesMatter ⬛️⬛️⬛️⬛️⬛️⬛️;
                add_header X-BlackLivesMatter ⬛️⬛️⬛️⬛️⬛️⬛️;
                add_header X-Drupal "#Drupal9 on Lagoon #CelebrateDrupal";
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
      - name: drush cron native
        schedule: "0 * * * *"
        command: drush cron
        service: cli