definitions:
  cronjobs:
    - &default-cron-5
      name: default cron 5
      schedule: "*/5 * * * *"
      command: drush --root=/app cron
      service: cli
    - &default-cron-15
      name: default cron 15
      schedule: "*/15 * * * *"
      command: drush --root=/app cron
      service: cli
    - &default-cron-native
      name: default cron native
      schedule: "0 * * * *"
      command: drush cron
      service: cli

docker-compose-yaml: docker-compose.yml

project: drupal8-example-advanced

tasks:
#   pre-rollout:
#     - run:
#         name: drush sql-dump
#         command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
#         service: cli

  post-rollout:
    # - run:
    #     name: drush cim
    #     command: drush -y cim
    #     service: cli
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli

environments:
  main:
    routes:
      # autogenerated default true
      # nginx.main.salvo-d8-ch1.ch4.amazee.io
      - nginx:
        # test acme
        # - salvo-d8.acme-true1.ch4.amazee.io:
        #     tls-acme: 'true'
        #     insecure: Redirect
        # - salvo-d8.acme-true2.ch4.amazee.io:
        #     tls-acme: "true"
        #     insecure: Redirect
        # - salvo-d8.acme-false1.ch4.amazee.io:
        #     tls-acme: 'false'
        #     insecure: Allow
        # - salvo-d8.acme-false2.ch4.amazee.io:
        #     tls-acme: "false"
        # custom route, using cluster domain
        - main-salvo-d8.ch4.amazee.io:
            insecure: Redirect
            annotations:
              # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#whitelist-source-range
              nginx.ingress.kubernetes.io/whitelist-source-range: |
                0.0.0.0/0
        - main-salvo-d8.dedyn.io:
            insecure: Redirect
            annotations:
              nginx.ingress.kubernetes.io/server-snippet: |
                add_header X-branch "#main";            
        - main-salvo-d8.duckdns.org:
            tls-acme: "true"
            annotations:
              nginx.ingress.kubernetes.io/server-snippet: |
                add_header X-branch "#main";
    cronjobs:
      - *default-cron-5
      - *default-cron-15
      - *default-cron-native
      - name: drush cron main native
        schedule: "0 * * * *"
        command: drush cron
        service: cli

  stage:
    routes:
      # nginx.stage.salvo-d8.de3.amazee.io
      - nginx:
        - stage-salvo-d8.duckdns.org:
            tls-acme: "true"
            insecure: Redirect
            annotations:
              nginx.ingress.kubernetes.io/server-snippet: |
                add_header X-branch "#stage";
    cronjobs:
      - *default-cron-5
      - *default-cron-15
      - *default-cron-native
      - name: ls env stage native
        schedule: "0 * * * *"
        command: ls
        service: cli
